name: My First CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code lo GitHub se
        uses: actions/checkout@v3

      - name: Python setup kro
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Pytest install kro
        run:  pip install pytest

      - name:  Tests chlao
        run:  pytest test_calculator.py

      - name:  DockerHub login kro
        uses:  docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_SECRET }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Docker image banao aur push kro
        uses: docker/build-push-action@v5
        with:
          context:  .
          push:  true
          tags:  amanat2662/calculator-app:latest
